/**
 * Idempotent seed script.
 *   npm run seed
 * Reads data/players_seed.json (generated by scripts/build_seed.py from a
 * refreshed ADP export) and upserts players + their initial per-category
 * player_ratings rows into Supabase using the service-role key.
 *
 * Safe to re-run: players are matched by `slug`, ratings are only inserted
 * where a (player, category) row doesn't already exist (so re-running never
 * clobbers live community ratings — only adds newly-seeded players).
 */
import { createClient } from '@supabase/supabase-js';
import fs from 'node:fs';
import path from 'node:path';
import { seedRatingFromRank, ELO_BASE_RATING } from '../lib/elo';
import type { Category, Position } from '../lib/database.types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in the environment.');
  console.error('Copy .env.example to .env.local, fill in your Supabase project values, then re-run.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

type SeedPlayer = {
  full_name: string;
  first_name: string;
  last_name: string;
  position: Position;
  nfl_team: string;
  team_abbreviation: string;
  bye_week: number;
  headshot_url: string | null;
  active: boolean;
  fantasy_relevant: boolean;
  slug: string;
  external_ref: string;
  seed_rank_overall: number | null;
  seed_rank_position: number;
};

const CATEGORY_BY_POSITION: Record<Position, Category> = {
  QB: 'qb', RB: 'rb', WR: 'wr', TE: 'te', K: 'k', DST: 'dst',
};

async function main() {
  const file = path.join(__dirname, '..', 'data', 'players_seed.json');
  const players: SeedPlayer[] = JSON.parse(fs.readFileSync(file, 'utf-8'));
  console.log(`Loaded ${players.length} players from ${file}`);

  const positionPoolSize: Record<string, number> = {};
  for (const p of players) {
    positionPoolSize[p.position] = (positionPoolSize[p.position] ?? 0) + 1;
  }
  const overallPoolSize = players.filter((p) => p.seed_rank_overall !== null).length;

  let upserted = 0;
  for (const batchStart of range(0, players.length, 50)) {
    const batch = players.slice(batchStart, batchStart + 50);
    const { data, error } = await supabase
      .from('players')
      .upsert(
        batch.map((p) => ({
          full_name: p.full_name,
          first_name: p.first_name,
          last_name: p.last_name,
          position: p.position,
          nfl_team: p.nfl_team,
          team_abbreviation: p.team_abbreviation,
          bye_week: p.bye_week,
          headshot_url: p.headshot_url,
          active: p.active,
          fantasy_relevant: p.fantasy_relevant,
          slug: p.slug,
          external_ref: p.external_ref,
          seed_rank_overall: p.seed_rank_overall,
          seed_rank_position: p.seed_rank_position,
        })),
        { onConflict: 'slug' }
      )
      .select('id, slug, position, seed_rank_overall, seed_rank_position');

    if (error) throw error;
    upserted += data?.length ?? 0;

    // Seed player_ratings for overall (if draft-relevant) + the player's own position.
    for (const row of data ?? []) {
      const categories: { category: Category; rank: number | null; poolSize: number }[] = [
        { category: CATEGORY_BY_POSITION[row.position as Position], rank: row.seed_rank_position, poolSize: positionPoolSize[row.position] },
      ];
      if (row.seed_rank_overall !== null) {
        categories.push({ category: 'overall', rank: row.seed_rank_overall, poolSize: overallPoolSize });
      }

      for (const { category, rank, poolSize } of categories) {
        const rating = rank ? seedRatingFromRank(rank, poolSize) : ELO_BASE_RATING;
        const { error: existingErr, data: existing } = await supabase
          .from('player_ratings')
          .select('player_id')
          .eq('player_id', row.id)
          .eq('category', category)
          .maybeSingle();
        if (existingErr) throw existingErr;
        if (existing) continue; // never overwrite a live rating on re-seed

        const { error: insertErr } = await supabase
          .from('player_ratings')
          .insert({ player_id: row.id, category, rating });
        if (insertErr) throw insertErr;
      }
    }
    console.log(`Upserted ${data?.length ?? 0} players (batch starting at ${batchStart})`);
  }

  console.log(`Done. Upserted ${upserted} players total.`);
}

function* range(start: number, end: number, step: number) {
  for (let i = start; i < end; i += step) yield i;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
