name: Feature request
description: Suggest an improvement for RankUp Fantasy.
title: "[Idea]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like us to add?
      placeholder: It would be useful if RankUp Fantasy could...
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: How would this improve the site?
    validations:
      required: true
